/* exams.js — mock exam question bank and exam definitions.
 *
 * This bank is SEPARATE from questions.js so that mock exams never repeat your
 * practice questions verbatim. Every question is original, written to test the same
 * knowledge areas as the WPI/ABC Wastewater Treatment Class I Need-to-Know Criteria.
 *
 * THESE ARE NOT ACTUAL EOCP OR WPI EXAM QUESTIONS. They are original practice
 * questions built around the published exam content outline.
 *
 * Question fields: { id, d:duty, lvl:difficulty 1-3, t:type, q, o:[options], a:index, e:explanation }
 *   d   : 'TPE' | 'EQP' | 'LAB' | 'SSA'  (matches the exam duty areas)
 *   lvl : 1 = basic, 2 = intermediate, 3 = difficult
 *   t   : 'mc' | 'calc' | 'sc'
 *
 * Exams are assembled by EXAM_DEFS below, weighted to the real duty distribution
 * (TPE 38%, EQP 39%, LAB 13%, SSA 10%).
 */

const MOCK_BANK = [
/* ---------------- TPE — Treatment Process Evaluation & Adjustment ---------------- */
{id:'e1',d:'TPE',lvl:1,t:'mc',q:'Which process removes the largest debris from incoming wastewater?',o:['Bar screening','Primary sedimentation','Aeration','Disinfection'],a:0,e:'Bar screens are the first unit and remove rags, sticks and large debris to protect downstream equipment.'},
{id:'e2',d:'TPE',lvl:1,t:'mc',q:'Grit removal primarily protects equipment from:',o:['Abrasion and wear','Corrosion by acids','Biological fouling','Electrical faults'],a:0,e:'Grit is dense and abrasive; it wears impellers and accumulates in tanks, stealing volume.'},
{id:'e3',d:'TPE',lvl:1,t:'mc',q:'Primary treatment removes solids by:',o:['Gravity settling','Biological oxidation','Chemical disinfection','Membrane filtration'],a:0,e:'Primary treatment is purely physical — gravity settling of settleable solids and skimming of floatables.'},
{id:'e4',d:'TPE',lvl:1,t:'mc',q:'The main product of secondary biological treatment is:',o:['Microbial cells that can be settled out','Chlorinated organic compounds','Grit and screenings','Dissolved oxygen'],a:0,e:'Biology converts dissolved BOD into settleable bacterial cells, which the secondary clarifier then removes.'},
{id:'e5',d:'TPE',lvl:1,t:'mc',q:'Which condition has no free dissolved oxygen but does contain nitrate?',o:['Anoxic','Aerobic','Anaerobic','Septic'],a:0,e:'Anoxic = nitrate present, no free DO. This is where denitrification occurs.'},
{id:'e6',d:'TPE',lvl:1,t:'mc',q:'Disinfection is best described as:',o:['Reducing pathogens to a safe level','Sterilising the water completely','Removing all suspended solids','Neutralising the pH'],a:0,e:'Disinfection reduces pathogens to a safe level. It is not sterilisation, which would destroy all organisms.'},
{id:'e7',d:'TPE',lvl:1,t:'mc',q:'In a facultative lagoon, the bottom layer is:',o:['Anaerobic','Aerobic','Fully mixed','Chlorinated'],a:0,e:'Facultative lagoons stratify: aerobic on top, facultative in the middle, anaerobic at the bottom.'},
{id:'e8',d:'TPE',lvl:1,t:'mc',q:'Coagulation works by:',o:['Neutralising the electrical charge on colloidal particles','Physically straining out particles','Dissolving suspended solids','Raising the water temperature'],a:0,e:'Coagulants neutralise the negative surface charge that keeps colloids repelling each other and suspended.'},
{id:'e9',d:'TPE',lvl:1,t:'mc',q:'Flocculation requires:',o:['Slow, gentle mixing','Violent rapid mixing','No mixing at all','High pressure'],a:0,e:'Gentle mixing lets destabilised particles collide and grow. Too much energy tears the floc apart.'},
{id:'e10',d:'TPE',lvl:1,t:'mc',q:'Waste activated sludge is:',o:['Excess biological solids removed to control sludge age','Sludge returned to the aeration basin','Grit collected at the headworks','Screenings sent to landfill'],a:0,e:'WAS is removed from the system to control the microbial population. RAS is what gets returned.'},
{id:'e11',d:'TPE',lvl:2,t:'mc',q:'An SVI of 175 most likely indicates:',o:['Filamentous bulking','Excellent settling','A very young sludge','Complete denitrification'],a:0,e:'Under 100 is good settling; over 150 indicates bulking, usually filamentous. Check DO first.'},
{id:'e12',d:'TPE',lvl:2,t:'sc',q:'The aeration basin shows dark brown, greasy foam and the effluent is turbid with fine particles. The most appropriate action is:',o:['Increase the wasting rate','Decrease the wasting rate','Stop returning sludge','Add coagulant to the aeration basin'],a:0,e:'Dark greasy foam plus pin floc indicates old, over-aged sludge. Increase wasting to reduce sludge age.'},
{id:'e13',d:'TPE',lvl:2,t:'sc',q:'A trickling filter has developed standing water on its surface. The operator should first:',o:['Increase recirculation to flush the media','Shut down the filter for two weeks','Add chlorine to the influent permanently','Reduce the media depth'],a:0,e:'Ponding means plugged media voids. Increased recirculation flushes them; raking and dose-flooding also help.'},
{id:'e14',d:'TPE',lvl:2,t:'mc',q:'Chlorine disinfection efficiency decreases as pH rises because:',o:['Less hypochlorous acid (HOCl) is present at higher pH','Chlorine evaporates faster at higher pH','Contact time is reduced at higher pH','Bacteria multiply faster at higher pH'],a:0,e:'The HOCl/OCl⁻ equilibrium shifts toward the weaker OCl⁻ as pH rises, reducing effectiveness.'},
{id:'e15',d:'TPE',lvl:2,t:'sc',q:'A primary clarifier is producing thin, watery sludge. The operator should:',o:['Reduce sludge pumping run time','Increase sludge pumping run time','Increase the influent flow','Add polymer to the clarifier centre well'],a:0,e:'Thin sludge means you are pumping past the blanket and drawing water. Reduce run time and check blanket depth before pumping.'},
{id:'e16',d:'TPE',lvl:2,t:'mc',q:'Recirculation on a trickling filter serves all of the following EXCEPT:',o:['Providing disinfection of the effluent','Diluting strong influent','Keeping the media continuously wet','Helping control filter flies and odour'],a:0,e:'Recirculation does not disinfect. It dilutes load, wets media, keeps the distributor turning and controls flies and odour.'},
{id:'e17',d:'TPE',lvl:2,t:'sc',q:'A coagulant is being fed but no floc forms. Which should be checked FIRST?',o:['pH of the water being treated','The effluent flow meter calibration','The digester gas production','The screenings bin level'],a:0,e:'Each coagulant has an effective pH window. Outside it, no dose will work. Check pH before adjusting dose.'},
{id:'e18',d:'TPE',lvl:2,t:'mc',q:'Which correctly pairs a chemical with its effect on alkalinity?',o:['Alum consumes alkalinity','Alum adds alkalinity','Caustic soda consumes alkalinity','Ferric chloride adds alkalinity'],a:0,e:'Metal salt coagulants (alum, ferric) consume alkalinity and lower pH. Caustic soda, lime and soda ash raise pH.'},
{id:'e19',d:'TPE',lvl:2,t:'sc',q:'Lagoon effluent fails its TSS limit but BOD is well within limits. The most likely cause is:',o:['Algae in the effluent','Failure of the disinfection system','Grit carryover from the headworks','Excessive chemical dosing'],a:0,e:'Algae are suspended solids. A well-treating lagoon commonly fails TSS purely because of algal carryover.'},
{id:'e20',d:'TPE',lvl:2,t:'mc',q:'The purpose of a chlorine contact chamber\'s serpentine baffles is to:',o:['Prevent short-circuiting so contact time is achieved','Increase the chlorine dose automatically','Settle out remaining solids','Aerate the effluent before discharge'],a:0,e:'Baffles force water along a long path so every portion receives the full design contact time.'},
{id:'e21',d:'TPE',lvl:3,t:'sc',q:'A secondary clarifier shows well-settled sludge rising in mats with gas bubbles, while the aeration basin has a sludge age of 18 days and DO of 4.5 mg/L. The BEST corrective action is:',o:['Increase RAS rate and reduce sludge age/aeration to limit nitrate','Decrease RAS rate and increase aeration','Add coagulant to the clarifier influent','Shut down the secondary clarifier'],a:0,e:'This is denitrification: a long sludge age and high DO produce nitrate, which denitrifies in the blanket and floats sludge. Increase RAS to shorten blanket detention, and reduce sludge age/DO to produce less nitrate.'},
{id:'e22',d:'TPE',lvl:3,t:'sc',q:'Influent BOD triples overnight with no flow increase, and within hours floc formation collapses. The most likely cause and first action are:',o:['An industrial slug load — sample upstream and protect the biology','Infiltration and inflow — reduce chemical dosing','Normal diurnal variation — take no action','Clarifier weir fouling — clean the weirs'],a:0,e:'High strength with normal flow is a slug load. Trace it upstream, notify pretreatment, and protect the aeration basin. I&I would show the opposite pattern (high flow, low strength).'},
{id:'e23',d:'TPE',lvl:3,t:'mc',q:'A plant is nitrifying and alkalinity has fallen from 220 to 60 mg/L as CaCO₃ over three weeks. The most likely consequence if uncorrected is:',o:['pH will crash and nitrification will fail','Alkalinity will recover naturally','BOD removal will improve','Sludge settling will improve'],a:0,e:'Nitrification consumes about 7.1 mg alkalinity per mg ammonia-N. With the buffer nearly gone, pH will drop sharply and the nitrifiers — which are pH sensitive — will fail.'},
{id:'e24',d:'TPE',lvl:3,t:'sc',q:'Coagulant dose was increased to improve a hazy effluent, but the effluent got worse. The most likely explanation is:',o:['Charge reversal has re-stabilised the particles','The coagulant has expired','The flocculator is running too slowly','Detention time is too long'],a:0,e:'Overdosing a coagulant can reverse the particle surface charge, re-stabilising the colloids. Back the dose off and re-run a jar test.'},
{id:'e25',d:'TPE',lvl:3,t:'calc',q:'A circular clarifier 22 m in diameter treats 5,000 m³/day. What is the surface overflow rate?',o:['13.2 m³/m²·day','3.3 m³/m²·day','52.6 m³/m²·day','227 m³/m²·day'],a:0,e:'r = 11 m. A = π × 121 = 380.1 m². SOR = 5,000 ÷ 380.1 = 13.2 m³/m²·day.'},
{id:'e26',d:'TPE',lvl:3,t:'calc',q:'A plant treats 8.0 ML/day with influent BOD 220 mg/L and effluent BOD 22 mg/L. What mass of BOD is removed per day?',o:['1,584 kg/day','1,760 kg/day','176 kg/day','198 kg/day'],a:0,e:'BOD removed as concentration = 220 − 22 = 198 mg/L. kg/day = 198 × 8.0 = 1,584 kg/day.'},
{id:'e27',d:'TPE',lvl:3,t:'calc',q:'A settleometer reads 360 mL/L and MLSS is 2,250 mg/L. What is the SVI, and what does it indicate?',o:['160 — bulking sludge','100 — good settling','80 — excellent settling','360 — normal'],a:0,e:'SVI = (360 × 1,000) ÷ 2,250 = 160. Above 150 indicates bulking; investigate DO and filaments.'},
{id:'e28',d:'TPE',lvl:3,t:'calc',q:'Aeration basin volume is 1.8 ML at MLSS 3,200 mg/L. Total solids leaving the system are 480 kg/day. What is the MCRT?',o:['12 days','9 days','15 days','6 days'],a:0,e:'Solids in system = 3,200 × 1.8 = 5,760 kg. MCRT = 5,760 ÷ 480 = 12 days.'},
{id:'e29',d:'TPE',lvl:2,t:'calc',q:'A jar test gives an optimum dose of 28 mg/L. Flow is 3.5 ML/day. How many kg/day of pure chemical is required?',o:['98 kg/day','9.8 kg/day','980 kg/day','8 kg/day'],a:0,e:'kg/day = mg/L × ML/day = 28 × 3.5 = 98 kg/day.'},
{id:'e30',d:'TPE',lvl:2,t:'calc',q:'A contact chamber holds 60 m³ and treats 4,320 m³/day. What is the contact time in minutes?',o:['20 minutes','30 minutes','15 minutes','45 minutes'],a:0,e:'DT = 60 ÷ 4,320 = 0.01389 days × 1,440 min/day = 20 minutes.'},
{id:'e31',d:'TPE',lvl:1,t:'calc',q:'Influent TSS is 250 mg/L and effluent TSS is 25 mg/L. What is the percent removal?',o:['90%','10%','75%','25%'],a:0,e:'(250 − 25) ÷ 250 × 100 = 90%.'},
{id:'e32',d:'TPE',lvl:1,t:'calc',q:'A tank is 10 m long, 5 m wide with water 3 m deep. What is its volume?',o:['150 m³','18 m³','50 m³','1,500 m³'],a:0,e:'V = 10 × 5 × 3 = 150 m³.'},
{id:'e33',d:'TPE',lvl:1,t:'mc',q:'Backwash water from a filter is normally sent:',o:['Back to the head of the plant','Directly to the receiving water','To the potable water system','To the screenings bin'],a:0,e:'Backwash water carries the solids removed by the filter and must be re-treated, so it returns to the head of the plant.'},
{id:'e34',d:'TPE',lvl:2,t:'mc',q:'Activated carbon removes dissolved organics by:',o:['Adsorption','Straining','Biological oxidation','Precipitation'],a:0,e:'Adsorption onto the carbon\'s internal surface area. Carbon eventually exhausts and must be replaced or regenerated.'},
{id:'e35',d:'TPE',lvl:2,t:'mc',q:'Which sequence is correct for chemical treatment?',o:['pH adjust → coagulant → rapid mix → polymer → slow mix → settle','Polymer → coagulant → settle → rapid mix','Coagulant → settle → polymer → rapid mix','Rapid mix → settle → coagulant → polymer'],a:0,e:'Coagulant always goes before polymer, with rapid mix for coagulation and slow mix for flocculation, then settling.'},

/* ---------------- EQP — Equipment Evaluation, Maintenance & Operation ---------------- */
{id:'e36',d:'EQP',lvl:1,t:'mc',q:'A gate valve should be used for:',o:['Isolation — fully open or fully closed','Precise throttling of flow','Preventing backflow automatically','Relieving excess pressure'],a:0,e:'Gate valves are isolation valves. Throttling with one erodes the seat and destroys the valve.'},
{id:'e37',d:'EQP',lvl:1,t:'mc',q:'A check valve\'s function is to:',o:['Prevent reverse flow','Throttle flow precisely','Isolate a line for maintenance','Measure flow rate'],a:0,e:'Check valves are automatic one-way valves, protecting pumps from backflow and reverse rotation.'},
{id:'e38',d:'EQP',lvl:1,t:'mc',q:'Which pump type delivers a nearly constant flow regardless of discharge head?',o:['Positive displacement','Centrifugal','Vertical turbine','Self-priming centrifugal'],a:0,e:'PD pumps move a fixed volume per cycle. Centrifugal pump flow falls as head rises.'},
{id:'e39',d:'EQP',lvl:1,t:'mc',q:'Priming a centrifugal pump means:',o:['Filling the casing and suction with liquid','Lubricating the bearings','Adjusting the packing gland','Setting the motor overload'],a:0,e:'A centrifugal pump cannot pump air, so it must be filled with liquid to develop suction.'},
{id:'e40',d:'EQP',lvl:1,t:'mc',q:'Fine-bubble diffusers compared with coarse-bubble diffusers:',o:['Transfer oxygen more efficiently','Transfer oxygen less efficiently','Require no maintenance','Cannot be used in activated sludge'],a:0,e:'Smaller bubbles give more surface area per volume of air and rise more slowly, so oxygen transfer efficiency is higher.'},
{id:'e41',d:'EQP',lvl:1,t:'mc',q:'Aeration typically accounts for what share of a treatment plant\'s energy use?',o:['The largest single share','Less than 5%','About 1%','None — aeration is passive'],a:0,e:'Aeration is typically 50–60% of plant electricity, making DO control the biggest energy lever an operator has.'},
{id:'e42',d:'EQP',lvl:2,t:'sc',q:'A pump is making a rattling noise like gravel and the discharge gauge is fluctuating wildly. The operator should investigate:',o:['The suction side for restriction or low level','The discharge check valve only','The motor windings','The effluent weir'],a:0,e:'This describes cavitation, which is caused by insufficient suction pressure — closed valve, plugged strainer, low wet well, or excessive lift.'},
{id:'e43',d:'EQP',lvl:2,t:'mc',q:'Running a positive displacement pump against a closed discharge valve will:',o:['Build pressure until something ruptures','Simply stop the pump safely','Reduce flow gradually to zero with no harm','Improve pump efficiency'],a:0,e:'A PD pump has no internal relief path. A pressure relief valve is mandatory to protect the pump and piping.'},
{id:'e44',d:'EQP',lvl:2,t:'sc',q:'A pump motor\'s amperage has increased 15% over six weeks with no change in process conditions. This suggests:',o:['A developing mechanical problem','Improved efficiency','A flow meter error','Normal seasonal variation'],a:0,e:'Rising amps mean increasing load — a partial clog, bearing wear, misalignment or rubbing. Investigate before failure.'},
{id:'e45',d:'EQP',lvl:2,t:'mc',q:'A properly adjusted pump packing gland should:',o:['Drip slowly to lubricate and cool the shaft','Remain completely dry','Leak in a continuous stream','Be tightened until no shaft movement is possible'],a:0,e:'Packing needs a slow drip for lubrication and cooling. A dry gland scores the shaft sleeve. Mechanical seals, by contrast, should not leak.'},
{id:'e46',d:'EQP',lvl:2,t:'sc',q:'Blower discharge pressure is climbing while delivered air flow drops. The FIRST item to check is:',o:['The blower inlet filter','The secondary clarifier weirs','The chlorine residual analyser','The digester heat exchanger'],a:0,e:'Check the cheap, common cause first: a plugged inlet filter starves the blower. Then investigate fouled diffusers downstream.'},
{id:'e47',d:'EQP',lvl:2,t:'sc',q:'A pump runs but delivers no flow. Which is LEAST likely to be the cause?',o:['The effluent weir needs cleaning','The pump has lost its prime','The impeller is clogged','The suction valve is closed'],a:0,e:'A dirty effluent weir does not stop a pump delivering flow. Lost prime, clogged impeller and a closed suction valve all do.'},
{id:'e48',d:'EQP',lvl:2,t:'mc',q:'Water hammer is caused by:',o:['A sudden change in flow velocity, such as rapid valve closure','Excessive dissolved oxygen','Low pH in the wastewater','Too much lubricant in a bearing'],a:0,e:'A rapid velocity change creates a pressure surge that can rupture pipe and damage equipment. Slow-closing valves help control it.'},
{id:'e49',d:'EQP',lvl:2,t:'mc',q:'Over-greasing a bearing:',o:['Can blow out the seals and cause failure','Is always beneficial','Has no effect either way','Extends bearing life indefinitely'],a:0,e:'Over-greasing builds pressure that ruptures seals and causes overheating. Follow the manufacturer\'s schedule and quantity.'},
{id:'e50',d:'EQP',lvl:2,t:'mc',q:'A VFD (variable frequency drive) saves energy by:',o:['Varying motor speed to match demand','Increasing the motor voltage','Reducing the number of pumps required','Eliminating the need for maintenance'],a:0,e:'A VFD varies frequency to control motor speed, so a pump or blower delivers only what is needed rather than being throttled.'},
{id:'e51',d:'EQP',lvl:2,t:'mc',q:'A rotating biological contactor typically operates at:',o:['About 40% submerged, about 1.5 rpm','Fully submerged, about 20 rpm','About 90% submerged, about 10 rpm','Above the water, about 5 rpm'],a:0,e:'~40% submergence and ~1.5 rpm lets the biofilm alternately contact wastewater and air.'},
{id:'e52',d:'EQP',lvl:3,t:'sc',q:'An RBC shaft has begun to slow and visibly sag. The most likely cause is:',o:['Excessive biomass accumulation on the first stage','Insufficient influent BOD','Excessive chlorine in the influent','The discs are too thin'],a:0,e:'Heavy first-stage biomass adds enormous weight, overloading bearings and the shaft — a known structural failure mode. Reduce first-stage loading or balance the load.'},
{id:'e53',d:'EQP',lvl:3,t:'sc',q:'A centrifuge has developed noticeable vibration during operation. The correct response is:',o:['Shut it down and inspect before running further','Increase the feed rate to smooth it out','Add more polymer and continue','Ignore it unless it becomes louder'],a:0,e:'Vibration indicates imbalance, worn bearings or scroll wear. Running through vibration risks catastrophic failure. Shut down and inspect.'},
{id:'e54',d:'EQP',lvl:3,t:'sc',q:'A filter bed has developed mudballs and cracks. The underlying cause is most likely:',o:['Backwash rate or duration insufficient to fluidise the bed','Backwash rate far too high','Excessive chlorine in the backwash water','Media that is too fine throughout'],a:0,e:'Inadequate backwash leaves solids behind, which compact into mudballs and cause the bed to crack and channel. Air scour and correct rate/duration fix it.'},
{id:'e55',d:'EQP',lvl:3,t:'mc',q:'Media loss into the backwash trough indicates:',o:['Backwash rate is too high','Backwash rate is too low','The influent turbidity is too low','The filter run time is too short'],a:0,e:'Excessive backwash rate over-expands the bed and carries media out. Too LOW a rate causes mudballs — the opposite problem.'},
{id:'e56',d:'EQP',lvl:3,t:'sc',q:'A UV disinfection system is failing bacteriological limits though lamps are within their rated hours and flow is normal. The most likely cause is:',o:['Fouled quartz sleeves reducing UV delivered to the water','A failed chlorine feed pump','Excessive dechlorination','Insufficient contact chamber baffling'],a:0,e:'Sleeve fouling is the number one cause of UV underperformance. Low UV transmittance from turbidity is the next thing to check.'},
{id:'e57',d:'EQP',lvl:3,t:'calc',q:'A wet well 3 m × 2.5 m drops 1.2 m in 5 minutes with inflow isolated. What is the pump rate in L/min?',o:['1,800 L/min','900 L/min','7,500 L/min','360 L/min'],a:0,e:'Volume = 3 × 2.5 × 1.2 = 9 m³ = 9,000 L. Rate = 9,000 ÷ 5 = 1,800 L/min.'},
{id:'e58',d:'EQP',lvl:3,t:'mc',q:'"Single phasing" on a three-phase motor means:',o:['Loss of one supply phase, causing overheating','The motor is running at half speed by design','Only one winding was installed','The motor is operating at peak efficiency'],a:0,e:'Losing one phase forces the remaining windings to carry excessive current, rapidly overheating and destroying the motor.'},
{id:'e59',d:'EQP',lvl:2,t:'mc',q:'NPSH available must be:',o:['Greater than the NPSH required by the pump','Less than the NPSH required by the pump','Exactly equal to zero','Irrelevant for wastewater pumps'],a:0,e:'If available NPSH falls below what the pump requires, the liquid flashes to vapour at the impeller and the pump cavitates.'},
{id:'e60',d:'EQP',lvl:2,t:'mc',q:'Total Dynamic Head (TDH) includes:',o:['Static lift plus friction losses plus pressure head','Only the vertical lift','Only friction losses','Only the pump discharge pressure rating'],a:0,e:'TDH is everything the pump must work against: static lift, friction through pipe and fittings, and any pressure head at the discharge.'},
{id:'e61',d:'EQP',lvl:1,t:'mc',q:'Preventive maintenance is best described as:',o:['Scheduled work performed to prevent failure','Repairs made after equipment breaks','Replacement of equipment at end of life','Cleaning performed only during inspections'],a:0,e:'PM is scheduled — lubrication, alignment, vibration checks, filter changes — and is far cheaper than corrective maintenance.'},
{id:'e62',d:'EQP',lvl:1,t:'mc',q:'A mechanical seal on a pump should:',o:['Not leak','Drip about once per second','Leak in a steady stream','Be greased weekly'],a:0,e:'Mechanical seals should show no leakage. Packing glands, by contrast, need a slow drip for cooling and lubrication.'},
{id:'e63',d:'EQP',lvl:2,t:'sc',q:'A valve that has not been operated in three years is found seized during an emergency. The best preventive practice is:',o:['Exercise valves on a regular schedule','Replace all valves annually','Leave valves partially open at all times','Remove the valves from the piping'],a:0,e:'Valves that sit in one position seize. Regular exercising as part of the PM programme keeps them functional when needed.'},
{id:'e64',d:'EQP',lvl:2,t:'mc',q:'A globe valve is preferred over a gate valve when you need to:',o:['Throttle and regulate flow','Fully isolate a line','Prevent backflow','Relieve pressure'],a:0,e:'Globe valves are designed to modulate flow. Gate valves are isolation-only and are damaged by throttling.'},
{id:'e65',d:'EQP',lvl:3,t:'sc',q:'A chemical metering pump is set correctly but chemical consumption is far higher than calculated. The LEAST likely cause is:',o:['The wastewater temperature has dropped 2 °C','The pump is out of calibration','There is a leak in the chemical line','The assumed solution strength is wrong'],a:0,e:'A small temperature change does not explain a large consumption discrepancy. Calibration error, leaks and wrong solution strength all do.'},
{id:'e66',d:'EQP',lvl:3,t:'mc',q:'Which is the correct method to verify a chemical metering pump\'s actual output?',o:['Timed drawdown using a calibration column','Reading the dial setting','Checking the motor nameplate','Measuring the discharge pressure'],a:0,e:'A dial setting is not a dose. Only a timed drawdown in a calibration column tells you what the pump actually delivers.'},
{id:'e67',d:'EQP',lvl:2,t:'mc',q:'Grit accumulating in a screen channel indicates:',o:['Approach velocity is too low','Approach velocity is too high','The screen bars are too closely spaced','The screenings bin is full'],a:0,e:'Below about 0.4 m/s, grit drops out in the channel. The design range through a screen is roughly 0.6–1.2 m/s.'},
{id:'e68',d:'EQP',lvl:1,t:'mc',q:'A magnetic flow meter requires:',o:['A full pipe and a conductive liquid','An open channel and clear water','A vacuum in the line','Compressed air injection'],a:0,e:'Mag meters work by electromagnetic induction, so the liquid must conduct and the pipe must run full.'},
{id:'e69',d:'EQP',lvl:2,t:'sc',q:'A Parshall flume has begun reading high. Which is NOT a plausible cause?',o:['The wastewater has become less conductive','The flume is no longer level','Solids have accumulated upstream','The level sensor has drifted'],a:0,e:'Conductivity affects magnetic meters, not flumes. Levelness, upstream solids and sensor drift all affect flume readings.'},
{id:'e70',d:'EQP',lvl:1,t:'mc',q:'The rotating distributor arm on a trickling filter must:',o:['Turn freely and distribute flow evenly','Remain stationary during operation','Rotate at exactly 60 rpm','Be submerged in the media'],a:0,e:'A stopped or uneven distributor quickly kills sections of the biofilm. Check orifices, bearings and seal regularly.'},

/* ---------------- LAB — Laboratory Analysis ---------------- */
{id:'e71',d:'LAB',lvl:1,t:'mc',q:'The BOD₅ test is incubated for:',o:['5 days at 20 °C in the dark','5 hours at 20 °C in the light','5 days at 35 °C in the light','2 hours at 150 °C'],a:0,e:'5 days, 20 °C, in the dark. Darkness prevents algal photosynthesis from adding oxygen and corrupting the result.'},
{id:'e72',d:'LAB',lvl:1,t:'mc',q:'Turbidity is reported in:',o:['NTU','mg/L','mL/L','ppm as CaCO₃'],a:0,e:'Nephelometric Turbidity Units, measured by the scattering of light by suspended particles.'},
{id:'e73',d:'LAB',lvl:1,t:'mc',q:'Settleable solids are reported in:',o:['mL/L','mg/L','NTU','% by mass'],a:0,e:'Measured in an Imhoff cone after one hour and reported as mL/L — a volume, not a mass concentration.'},
{id:'e74',d:'LAB',lvl:1,t:'mc',q:'Which parameter must be measured immediately on a grab sample?',o:['Dissolved oxygen','BOD₅','Total phosphorus','Total suspended solids'],a:0,e:'DO, pH, temperature and chlorine residual all change immediately on removal from the process.'},
{id:'e75',d:'LAB',lvl:1,t:'mc',q:'Total suspended solids samples are dried at:',o:['103–105 °C','550 °C','20 °C','200 °C'],a:0,e:'Dry at 103–105 °C. Ignition at 550 °C determines the volatile (organic) fraction.'},
{id:'e76',d:'LAB',lvl:2,t:'mc',q:'A 24-hour flow-proportional composite sample is preferred for permit BOD because it:',o:['Represents the true daily mass loading','Is faster to collect than a grab','Requires no preservation','Eliminates the need for laboratory QC'],a:0,e:'Weighting portions by flow means the composite reflects actual mass load rather than over-representing low-flow periods.'},
{id:'e77',d:'LAB',lvl:2,t:'sc',q:'A bacteriological sample from a chlorinated effluent returns invalid. The most likely cause is:',o:['No dechlorinating agent was in the bottle','The bottle was too large','The sample was collected at midday','The sample was chilled to 4 °C'],a:0,e:'Without a dechlorinating agent (usually sodium thiosulphate), chlorine keeps killing organisms in the bottle, invalidating the count.'},
{id:'e78',d:'LAB',lvl:2,t:'mc',q:'Volatile suspended solids are determined by:',o:['Igniting the dried filter at 550 °C and measuring weight loss','Filtering and weighing only','Titration with sulphuric acid','Measuring light scattering'],a:0,e:'What burns off at 550 °C is the volatile (organic) portion; the ash remaining is the fixed (inorganic) portion.'},
{id:'e79',d:'LAB',lvl:2,t:'sc',q:'Duplicate TSS results differ by 40%. Which is the LEAST likely cause?',o:['The sample was collected at 08:00 instead of 09:00','The sample was not mixed before pouring','The filters were not dried to constant weight','The balance is out of calibration'],a:0,e:'Collection time does not cause poor duplicate agreement on the same sample. Mixing, drying and balance calibration all do.'},
{id:'e80',d:'LAB',lvl:2,t:'mc',q:'Chain of custody documentation is required for:',o:['Samples used for regulatory or legal purposes','Every sample without exception','Only samples analysed on site','Only samples that exceed a limit'],a:0,e:'Regulatory and legal samples need an unbroken documented trail of possession and handling.'},
{id:'e81',d:'LAB',lvl:2,t:'mc',q:'COD compared to BOD on the same sample will be:',o:['Higher, and available much sooner','Lower, and available much sooner','Identical','Higher, but take 5 days longer'],a:0,e:'COD chemically oxidises material bacteria cannot use, so it is always higher, and it takes about 2 hours versus 5 days.'},
{id:'e82',d:'LAB',lvl:3,t:'sc',q:'A DO probe reads low throughout the plant, including in a sample you know is near saturation. The most likely cause is:',o:['A fouled membrane or depleted electrolyte','Genuinely low oxygen everywhere','Excessive chlorine residual','Water temperature slightly above normal'],a:0,e:'A consistent low bias across all points including a known-good sample points to the instrument, not the process. Service the membrane and electrolyte, then recalibrate.'},
{id:'e83',d:'LAB',lvl:3,t:'sc',q:'BOD results have come back unreasonably low for two weeks while COD is unchanged. The most likely explanation is:',o:['A toxic substance is inhibiting the seed bacteria','The plant is treating far better than before','The COD test is faulty','The samples were over-diluted with distilled water only'],a:0,e:'BOD is a biological test. A toxicant inhibits the seed organisms and suppresses BOD, while COD — a chemical test — is unaffected. That divergence is the clue.'},
{id:'e84',d:'LAB',lvl:3,t:'mc',q:'The classic reference (titration) method for dissolved oxygen is the:',o:['Winkler method','Gravimetric method','Nephelometric method','Breakpoint method'],a:0,e:'The Winkler iodometric titration is the reference method against which DO probes are validated.'},
{id:'e85',d:'LAB',lvl:3,t:'calc',q:'A settleometer reads 300 mL/L and MLSS is 2,000 mg/L. What is the SVI?',o:['150','200','100','66'],a:0,e:'SVI = (300 × 1,000) ÷ 2,000 = 150. This sits right at the bulking threshold — monitor closely.'},
{id:'e86',d:'LAB',lvl:2,t:'calc',q:'Influent BOD is 180 mg/L and effluent BOD is 9 mg/L. What is the percent removal?',o:['95%','90%','5%','171%'],a:0,e:'(180 − 9) ÷ 180 × 100 = 171 ÷ 180 × 100 = 95%.'},
{id:'e87',d:'LAB',lvl:1,t:'mc',q:'Which bottle must never be rinsed with the sample?',o:['A sterile bacteriological bottle','A plastic TSS bottle','A composite carboy','A turbidity vial'],a:0,e:'Rinsing destroys sterility and removes any preservative or dechlorinating agent already present in the bottle.'},
{id:'e88',d:'LAB',lvl:2,t:'mc',q:'Running a known standard alongside your samples is done to:',o:['Verify the accuracy of the method and instrument','Increase the sample volume','Satisfy the chain of custody','Reduce the hold time required'],a:0,e:'Standards verify accuracy; duplicates verify precision. Both are core laboratory quality control.'},

/* ---------------- SSA — Security, Safety & Administrative Procedures ---------------- */
{id:'e89',d:'SSA',lvl:1,t:'mc',q:'The correct order for testing a confined space atmosphere is:',o:['Oxygen, flammable, toxic','Toxic, flammable, oxygen','Flammable, toxic, oxygen','Any order is acceptable'],a:0,e:'Oxygen first — flammable gas meters need oxygen to read correctly, so an oxygen-deficient atmosphere makes that reading unreliable.'},
{id:'e90',d:'SSA',lvl:1,t:'mc',q:'The acceptable oxygen range for confined space entry is:',o:['19.5% to 23.5%','16% to 25%','12% to 28%','Exactly 21%'],a:0,e:'Below 19.5% is deficient; above 23.5% is enriched and a severe fire hazard. Both limits are examinable.'},
{id:'e91',d:'SSA',lvl:1,t:'mc',q:'In the hierarchy of controls, PPE ranks:',o:['Last','First','Second','It is not part of the hierarchy'],a:0,e:'Elimination → Substitution → Engineering → Administrative → PPE. PPE protects only the wearer and only if used correctly.'},
{id:'e92',d:'SSA',lvl:1,t:'mc',q:'WHMIS 2015 requires all of the following EXCEPT:',o:['Annual replacement of all chemical containers','Supplier and workplace labels','Safety Data Sheets','Worker education and training'],a:0,e:'The three pillars are labels, SDSs and training. There is no requirement to replace containers annually.'},
{id:'e93',d:'SSA',lvl:1,t:'mc',q:'When diluting concentrated acid, you should always:',o:['Add acid to water','Add water to acid','Add both simultaneously','Heat the water first'],a:0,e:'Always add acid TO water. The reaction is violently exothermic; the reverse can boil and spatter acid.'},
{id:'e94',d:'SSA',lvl:2,t:'sc',q:'Working in a wet well, you notice the rotten-egg odour has vanished. You should:',o:['Evacuate immediately','Continue working as the hazard has cleared','Remove your respirator to check','Increase the pump rate and continue'],a:0,e:'H₂S paralyses the sense of smell at dangerous concentrations. Losing the odour signals MORE danger, not less.'},
{id:'e95',d:'SSA',lvl:2,t:'sc',q:'A coworker collapses inside a digester. The correct action is:',o:['Do not enter; summon rescue and use retrieval equipment from outside','Enter immediately to help','Enter with another worker for safety','Wait ten minutes to see if they recover'],a:0,e:'The majority of confined space fatalities are would-be rescuers. Never enter without training and proper equipment.'},
{id:'e96',d:'SSA',lvl:2,t:'mc',q:'During lockout/tagout, a personal lock may be removed by:',o:['Only the worker who applied it','Any supervisor on shift','Any certified operator','The maintenance manager'],a:0,e:'Each worker applies and removes their own lock. This guarantees no one re-energises equipment someone else is still working on.'},
{id:'e97',d:'SSA',lvl:2,t:'mc',q:'Two steps commonly omitted from lockout/tagout are:',o:['Releasing stored energy and verifying zero energy','Filing a permit and notifying the supplier','Testing the atmosphere and posting a guard','Calibrating instruments and logging amps'],a:0,e:'Stored energy — pressure, springs, gravity, capacitors, heat — must be released, and zero energy verified by attempting to start.'},
{id:'e98',d:'SSA',lvl:2,t:'sc',q:'A chemical splash reaches an operator\'s eyes. The correct first aid is:',o:['Flush at the eyewash for at least 15 minutes and seek medical attention','Neutralise with a weak opposing chemical','Apply ointment and continue working','Rinse briefly and return to work'],a:0,e:'Flush for at least 15 minutes holding the eyelids open, then get medical attention. Never attempt chemical neutralisation on tissue.'},
{id:'e99',d:'SSA',lvl:2,t:'mc',q:'Hydrogen sulphide gas relative to air is:',o:['Heavier, so it collects in low points','Lighter, so it collects at the top','The same density as air','Only present above 40 °C'],a:0,e:'H₂S is heavier than air and pools in low areas — wet wells, sumps and manholes. Methane, by contrast, is lighter and collects high.'},
{id:'e100',d:'SSA',lvl:3,t:'sc',q:'You discover a permit limit exceedance in yesterday\'s results. The correct action is:',o:['Verify, correct the cause, document, and report within the required timeframe','Re-sample until a passing result is obtained and report that one','Wait for the monthly report to include it','Adjust the recorded value to fall within the limit'],a:0,e:'Verify, correct, document and report promptly. Selective re-sampling or altering records is falsification — the most serious operator offence.'},
{id:'e101',d:'SSA',lvl:3,t:'mc',q:'Which federal regulation sets national baseline effluent standards for Canadian wastewater systems?',o:['The Wastewater Systems Effluent Regulations (WSER)','The Municipal Wastewater Regulation','The Environmental Management Act','The Drinking Water Protection Regulation'],a:0,e:'WSER sits under the Fisheries Act and sets national baseline standards. The MWR and EMA are BC provincial instruments.'},
{id:'e102',d:'SSA',lvl:3,t:'mc',q:'EOCP certification is maintained by:',o:['Accumulating Continuing Education Units (CEUs)','Rewriting the exam every year','Working a set number of overtime hours','Holding a professional engineering designation'],a:0,e:'CEUs are required to renew EOCP certification. Track them as you earn them.'},
{id:'e103',d:'SSA',lvl:3,t:'sc',q:'You are asked to sign off on lab data you did not collect and believe may be inaccurate. You should:',o:['Decline to sign and escalate your concern in writing','Sign it since a supervisor requested it','Sign it but add a verbal comment','Alter the data to what you believe is correct'],a:0,e:'Never certify data you cannot verify. Escalate in writing. Falsifying or misrepresenting records is a serious regulatory and professional offence.'},
{id:'e104',d:'SSA',lvl:3,t:'mc',q:'The operator certification level a facility requires is determined by:',o:['The facility classification based on size and complexity','The number of staff employed','The plant\'s age','The chemical inventory volume'],a:0,e:'Facilities are classified by size and complexity, which sets the required certification level and the operator in responsible charge.'},
{id:'e105',d:'SSA',lvl:3,t:'sc',q:'A chlorine gas leak is detected at the chlorine building. The correct immediate response is:',o:['Evacuate upwind and uphill and activate the emergency plan','Spray water on the leak to absorb the gas','Enter with a dust mask to close the valve','Open all doors and continue normal operations'],a:0,e:'Evacuate upwind and uphill. Only trained responders with SCBA may enter. Never apply water to a chlorine leak — it forms corrosive acid and worsens the release.'},
{id:'e106',d:'SSA',lvl:2,t:'mc',q:'An unlabelled container of unknown chemical is found in the plant. You should:',o:['Not use it, isolate it, and label it properly once identified','Use it if it looks familiar','Pour it into the nearest drain','Store it with the other chemicals unlabelled'],a:0,e:'WHMIS requires every container be labelled. An unidentified chemical must be treated as hazardous and isolated until identified.'},
{id:'e107',d:'SSA',lvl:1,t:'mc',q:'Operating logs and lab records are:',o:['A legal requirement and evidence of compliance','Optional internal notes','Needed only when SCADA fails','Required only during regulatory inspections'],a:0,e:'Records are legally required and constitute the plant\'s proof of proper operation.'},
{id:'e108',d:'SSA',lvl:1,t:'mc',q:'Chlorine must never be mixed with:',o:['Acid or ammonia','Water','Sodium hydroxide in a separate tank','Air'],a:0,e:'Chlorine plus acid releases chlorine gas; chlorine plus ammonia forms chloramine vapours. Both are life-threatening.'}
];

/* Exam definitions.
   levels : which difficulty tiers this exam draws from
   n      : total questions
   start  : starting index into each duty's (fixed-order) pool. Different start
            values give each exam a different window of questions, which is what
            keeps the five exams from largely repeating one another.
   Duty weighting mirrors the real exam: TPE 38%, EQP 39%, LAB 13%, SSA 10%. */
const EXAM_DEFS = [
  {id:'mock1', name:'Mock Exam 1 — Basic', n:30, levels:[1], start:0, mins:45,
   desc:'Foundation recall across all four duty areas. Build confidence and confirm the basics are solid.'},
  {id:'mock2', name:'Mock Exam 2 — Intermediate', n:35, levels:[1,2], start:6, mins:55,
   desc:'Mixed recall and application. Closer to the real balance of question types.'},
  {id:'mock3', name:'Mock Exam 3 — Difficult', n:35, levels:[2,3], start:0, mins:60,
   desc:'Application and scenario-heavy, with the harder calculations. This one is meant to hurt a little.'},
  {id:'mock4', name:'Mock Exam 4 — Exam Simulation', n:40, levels:[1,2,3], start:0, mins:70,
   desc:'Full duty weighting and difficulty mix, timed. Treat it like the real thing — no notes, no pausing.'},
  {id:'mock5', name:'Mock Exam 5 — Final Assessment', n:40, levels:[1,2,3], start:17, mins:70,
   desc:'Your readiness benchmark. Score 80%+ here with no duty area below 70% and you are in good shape.'}
];

/* Duty weighting used to assemble each exam */
const DUTY_WEIGHT = { TPE:0.38, EQP:0.39, LAB:0.13, SSA:0.10 };

window.MOCK_BANK = MOCK_BANK;
window.EXAM_DEFS = EXAM_DEFS;
window.DUTY_WEIGHT = DUTY_WEIGHT;
