/* questions.js — practice question bank.
 *
 * Every question: { id, m:moduleId, l:lessonId, t:type, q:text, o:[options], a:answerIndex, e:explanation }
 * type: 'mc' = multiple choice knowledge, 'sc' = operator/scenario, 'calc' = calculation
 *
 * These feed BOTH the per-lesson practice questions and the per-module section tests.
 * Mock exam questions live separately in exams.js so the two banks never collide.
 *
 * To add your own question, copy any object below and change the fields.
 * Answer index is zero-based: 0 = first option.
 */

const QUESTIONS = [
/* ================= MODULE 1 ================= */
{id:'q1',m:'m1',l:'m1l1',t:'mc',q:'What is the primary purpose of wastewater treatment?',
 o:['To protect public health','To produce drinking water','To generate biogas for energy','To reduce the cost of water supply'],a:0,
 e:'Protection of public health is always the primary purpose. Environmental protection of the receiving water is the second purpose. Energy recovery is a by-product, not a purpose.'},
{id:'q2',m:'m1',l:'m1l1',t:'mc',q:'"Effluent" refers to:',
 o:['Water flowing out of a plant or process unit','Water flowing into a plant or process unit','Settled sludge at the bottom of a clarifier','Floating scum on a tank surface'],a:0,
 e:'Effluent flows OUT. Influent flows IN. Read carefully — many exam questions hinge on which one is meant.'},
{id:'q3',m:'m1',l:'m1l2',t:'mc',q:'Groundwater entering sewers through cracks and defective joints is called:',
 o:['Infiltration','Inflow','Interflow','Percolation'],a:0,
 e:'Infiltration = groundwater through cracks and defects. Inflow = surface water through direct connections such as roof drains and manhole covers.'},
{id:'q4',m:'m1',l:'m1l2',t:'sc',q:'During heavy rain, plant flow triples while influent BOD drops to 60 mg/L. The most likely explanation is:',
 o:['Infiltration and inflow diluting the wastewater','An industrial slug load','A failing primary clarifier','Excessive sludge recycling'],a:0,
 e:'High flow with LOW strength is the signature of I&I. A slug load would show normal or high flow with much HIGHER strength.'},
{id:'q5',m:'m1',l:'m1l2',t:'mc',q:'Typical raw domestic wastewater BOD₅ is approximately:',
 o:['200 mg/L','20 mg/L','1,000 mg/L','5,000 mg/L'],a:0,
 e:'About 200 mg/L BOD and 200–250 mg/L TSS are the anchor values for raw domestic wastewater. Memorise them.'},
{id:'q6',m:'m1',l:'m1l3',t:'mc',q:'Which statement about COD and BOD is correct?',
 o:['COD is always higher than BOD and is measured much faster','BOD is always higher than COD','They are always equal','COD takes 5 days and BOD takes 2 hours'],a:0,
 e:'COD chemically oxidises everything oxidisable including material bacteria cannot use, so it always exceeds BOD. COD takes about 2 hours; BOD₅ takes 5 days.'},
{id:'q7',m:'m1',l:'m1l3',t:'sc',q:'Influent arrives black with a strong rotten-egg odour. This indicates:',
 o:['Septic conditions producing hydrogen sulphide','An oxygen-enriched influent','Excessive chlorine residual','Normal fresh domestic wastewater'],a:0,
 e:'Black colour plus rotten-egg odour means septic — no dissolved oxygen, generating hydrogen sulphide. It also means a corrosion and H₂S exposure hazard.'},
{id:'q8',m:'m1',l:'m1l3',t:'mc',q:'Fecal coliform bacteria are used in wastewater testing as:',
 o:['An indicator organism suggesting possible fecal contamination','The most dangerous pathogen present','A measure of organic loading','A measure of dissolved oxygen'],a:0,
 e:'Testing every pathogen is impractical. Fecal coliforms are easy to count and indicate fecal contamination, so pathogens may be present.'},
{id:'q9',m:'m1',l:'m1l4',t:'mc',q:'Volatile solids are best described as:',
 o:['The organic fraction, burned off at 550 °C','The inorganic ash remaining after ignition','Solids that pass through a filter','Solids that settle in one hour'],a:0,
 e:'Volatile = organic = burns off at 550 °C. Fixed = inorganic = the ash left behind.'},
{id:'q10',m:'m1',l:'m1l4',t:'mc',q:'The pH range generally required for healthy biological treatment is:',
 o:['6.5 to 8.5','2.0 to 4.0','9.5 to 11.0','4.0 to 5.5'],a:0,
 e:'Biological treatment operates best from 6.5 to 8.5, ideally near neutral. Outside roughly 6–9 the organisms slow badly and may die.'},
{id:'q11',m:'m1',l:'m1l4',t:'mc',q:'Settleable solids are measured in an Imhoff cone and reported as:',
 o:['mL/L after one hour','mg/L after 24 hours','NTU after 30 minutes','Percent by weight'],a:0,
 e:'Imhoff cone, one hour, reported in mL/L. This unit trips people up — it is a volume, not a mass concentration.'},
{id:'q12',m:'m1',l:'m1l4',t:'calc',q:'A plant treats 4,500 m³/day. Influent BOD is 210 mg/L and effluent BOD is 18 mg/L. What is the percent BOD removal?',
 o:['91.4%','82.0%','8.6%','96.2%'],a:0,
 e:'% removal = (In − Out) ÷ In × 100 = (210 − 18) ÷ 210 × 100 = 192 ÷ 210 × 100 = 91.4%. Flow is not needed for a percent removal.'},

/* ================= MODULE 2 ================= */
{id:'q13',m:'m2',l:'m2l1',t:'mc',q:'The primary purpose of a bar screen is to:',
 o:['Protect downstream pumps and equipment from large debris','Remove dissolved organic matter','Settle out grit and sand','Disinfect the incoming wastewater'],a:0,
 e:'Screens protect downstream equipment. They remove no dissolved material and are not intended to settle grit.'},
{id:'q14',m:'m2',l:'m2l1',t:'sc',q:'The water level upstream of the bar screen is rising steadily. The most likely cause is:',
 o:['The screen is blinded with debris','The influent pump has failed','The grit chamber is overloaded','Effluent flow has increased'],a:0,
 e:'Rising upstream level across a screen means blinding — the openings are plugged and headloss is increasing. Rake or clear it.'},
{id:'q15',m:'m2',l:'m2l1',t:'mc',q:'How does a comminutor differ from a bar screen?',
 o:['A comminutor grinds solids and leaves them in the flow; a screen removes them','A comminutor removes solids; a screen grinds them','They are the same device','A comminutor only operates on grit'],a:0,
 e:'This is a classic exam distinction. Comminutors macerate solids so they stay in the flow; screens physically remove material for landfill.'},
{id:'q16',m:'m2',l:'m2l2',t:'mc',q:'The design velocity in a horizontal-flow grit channel is approximately:',
 o:['0.3 m/s (1 ft/s)','1.5 m/s (5 ft/s)','0.03 m/s (0.1 ft/s)','3.0 m/s (10 ft/s)'],a:0,
 e:'0.3 m/s (1 ft/s) is the classic target. It is fast enough to keep organics suspended but slow enough for dense grit to settle.'},
{id:'q17',m:'m2',l:'m2l2',t:'sc',q:'Grit removed from the grit chamber is black, greasy and smells strongly. The most likely cause is:',
 o:['Channel velocity is too low, so organics are settling with the grit','Channel velocity is too high','The grit chamber is undersized','Too much chlorine is being added upstream'],a:0,
 e:'Low velocity lets light organic material settle along with the grit, producing putrescible grit. Increase velocity (or air rate in an aerated chamber).'},
{id:'q18',m:'m2',l:'m2l2',t:'mc',q:'The main reason for removing grit early in the process is to prevent:',
 o:['Abrasion of equipment and loss of tank volume','Excessive BOD loading on aeration','Foaming in the aeration basin','Chlorine demand in the contact chamber'],a:0,
 e:'Grit is abrasive and dense. It wears pumps and mixers and accumulates in clarifiers and digesters, stealing volume.'},
{id:'q19',m:'m2',l:'m2l3',t:'mc',q:'Which flow measuring device requires a full pipe and a conductive liquid?',
 o:['Magnetic flow meter','Parshall flume','V-notch weir','Cipolletti weir'],a:0,
 e:'A magnetic meter uses electromagnetic induction, so it needs a conductive liquid and a completely full pipe. Flumes and weirs are open-channel devices.'},
{id:'q20',m:'m2',l:'m2l3',t:'mc',q:'Which weir gives the best accuracy at low flow rates?',
 o:['V-notch (triangular) weir','Rectangular weir','Cipolletti weir','Broad-crested weir'],a:0,
 e:'The V-notch shape means a small change in flow produces a relatively large change in head, giving good resolution at low flows.'},
{id:'q21',m:'m2',l:'m2l3',t:'sc',q:'A Parshall flume has read consistently high for two weeks. Which is the LEAST likely cause?',
 o:['The wastewater has become more conductive','The flume is not level','Solids have accumulated upstream of the flume','The level sensor has drifted out of calibration'],a:0,
 e:'Conductivity does not affect a flume — that matters for magnetic meters. Levelness, upstream solids and sensor calibration all directly affect flume readings.'},
{id:'q22',m:'m2',l:'m2l3',t:'calc',q:'A channel is 0.8 m wide with water 0.5 m deep, and the velocity is 0.6 m/s. What is the flow rate?',
 o:['0.24 m³/s','0.96 m³/s','2.4 m³/s','0.024 m³/s'],a:0,
 e:'Q = V × A. Area = 0.8 × 0.5 = 0.4 m². Q = 0.6 m/s × 0.4 m² = 0.24 m³/s.'},

/* ================= MODULE 3 ================= */
{id:'q23',m:'m3',l:'m3l1',t:'mc',q:'A well-operated primary clarifier typically removes what percentage of TSS?',
 o:['50–70%','5–10%','85–95%','25–40%'],a:0,
 e:'Primary clarifiers remove 50–70% of TSS and 25–40% of BOD. Do not confuse the two figures — 25–40% is the BOD number.'},
{id:'q24',m:'m3',l:'m3l1',t:'mc',q:'Surface Overflow Rate (SOR) is calculated as:',
 o:['Flow ÷ Surface Area','Flow ÷ Volume','Volume ÷ Flow','Flow ÷ Weir Length'],a:0,
 e:'SOR = Flow ÷ Surface Area, effectively the upward water velocity. Flow ÷ Weir Length is the weir overflow rate; Volume ÷ Flow is detention time.'},
{id:'q25',m:'m3',l:'m3l1',t:'sc',q:'Sludge is rising to the surface of a primary clarifier in clumps with gas bubbles. The correct response is to:',
 o:['Increase the frequency of sludge withdrawal','Decrease the frequency of sludge withdrawal','Increase the influent flow rate','Add coagulant to the clarifier'],a:0,
 e:'The sludge has gone septic from sitting too long, producing gas that floats it. Pull sludge more often. (In a SECONDARY clarifier, the same symptom usually means denitrification.)'},
{id:'q26',m:'m3',l:'m3l1',t:'mc',q:'Typical detention time in a primary clarifier is:',
 o:['1.5 to 2.5 hours','10 to 20 minutes','8 to 12 hours','2 to 3 days'],a:0,
 e:'1.5–2.5 hours. Too short and solids do not reach the bottom; too long and the sludge goes septic.'},
{id:'q27',m:'m3',l:'m3l1',t:'calc',q:'A rectangular primary clarifier is 24 m long, 6 m wide and 3 m deep, treating 1,700 m³/day. What is the detention time in hours?',
 o:['6.1 hours','2.5 hours','0.16 hours','12.2 hours'],a:0,
 e:'Volume = 24 × 6 × 3 = 432 m³. DT = Volume ÷ Flow = 432 ÷ 1,700 = 0.254 days. × 24 = 6.1 hours. (Long for a primary — this one is hydraulically underloaded.)'},
{id:'q28',m:'m3',l:'m3l1',t:'calc',q:'A circular clarifier is 20 m in diameter and treats 2,500 m³/day. What is the surface overflow rate?',
 o:['7.96 m³/m²·day','3.98 m³/m²·day','125 m³/m²·day','31.8 m³/m²·day'],a:0,
 e:'Radius = 20 ÷ 2 = 10 m. Area = π × 10² = 314.2 m². SOR = 2,500 ÷ 314.2 = 7.96 m³/m²·day. Using diameter instead of radius is the classic error.'},

/* ================= MODULE 4 ================= */
{id:'q29',m:'m4',l:'m4l1',t:'mc',q:'The target dissolved oxygen concentration in a conventional activated sludge aeration basin is:',
 o:['1.5 to 2.0 mg/L','0.1 to 0.3 mg/L','6.0 to 8.0 mg/L','10 to 12 mg/L'],a:0,
 e:'1.5–2.0 mg/L. Below about 0.5 mg/L treatment suffers and filaments take over; far above 3 mg/L simply wastes electricity.'},
{id:'q30',m:'m4',l:'m4l1',t:'mc',q:'An "anoxic" condition means:',
 o:['No free dissolved oxygen, but nitrate is present','No oxygen and no nitrate present','Free dissolved oxygen is present','Oxygen is above saturation'],a:0,
 e:'Anoxic = nitrate present, no free DO — this is where denitrification happens. Anaerobic = neither DO nor nitrate.'},
{id:'q31',m:'m4',l:'m4l1',t:'mc',q:'Secondary biological treatment primarily works by:',
 o:['Converting dissolved BOD into settleable microbial cells','Filtering out dissolved solids','Chemically precipitating organic matter','Disinfecting the wastewater'],a:0,
 e:'Gravity cannot remove dissolved BOD. Biology converts it into bacterial cells, which are then settled out in the secondary clarifier.'},
{id:'q32',m:'m4',l:'m4l2',t:'mc',q:'An SVI of 210 indicates:',
 o:['Bulking sludge that settles poorly','Excellent settling characteristics','A very young sludge','Complete nitrification'],a:0,
 e:'SVI under 100 = good settling. Over 150 = bulking, usually filamentous. 210 is clearly bulking.'},
{id:'q33',m:'m4',l:'m4l2',t:'sc',q:'The aeration basin has thick white billowy foam and MLSS is lower than normal. The correct action is:',
 o:['Reduce the wasting rate to build up the microbial population','Increase the wasting rate','Increase the RAS rate sharply','Add chlorine to the aeration basin'],a:0,
 e:'White billowy foam with low MLSS means a young sludge / high F/M — you have wasted too much. Reduce wasting so the population rebuilds.'},
{id:'q34',m:'m4',l:'m4l2',t:'sc',q:'Filamentous bulking has been confirmed by microscope. Which should you investigate FIRST?',
 o:['Low dissolved oxygen in the aeration basin','The chlorine residual in the effluent','The grit chamber velocity','The digester temperature'],a:0,
 e:'Low DO is the most common cause of filamentous bulking. Also consider low F/M, nutrient deficiency and septic influent. Chlorinating RAS is a last resort, not a first step.'},
{id:'q35',m:'m4',l:'m4l2',t:'mc',q:'In activated sludge, wasting rate primarily controls:',
 o:['Sludge age and MLSS concentration','The clarifier sludge blanket depth','Dissolved oxygen concentration','Influent flow rate'],a:0,
 e:'Wasting controls sludge age/MLSS. RAS rate controls the blanket. Keeping these two roles straight is essential.'},
{id:'q36',m:'m4',l:'m4l2',t:'calc',q:'A settleometer shows 280 mL/L settled after 30 minutes. MLSS is 2,800 mg/L. What is the SVI?',
 o:['100','280','2.8','1,000'],a:0,
 e:'SVI = (settled mL/L × 1000) ÷ MLSS = (280 × 1000) ÷ 2800 = 280,000 ÷ 2,800 = 100. An SVI of 100 is good settling.'},
{id:'q37',m:'m4',l:'m4l3',t:'mc',q:'A rotating biological contactor (RBC) normally operates:',
 o:['About 40% submerged at about 1.5 rpm','Fully submerged at 15 rpm','About 90% submerged at 0.1 rpm','Completely above water at 30 rpm'],a:0,
 e:'~40% submerged, ~1.5 rpm. The rotation alternately exposes the biofilm to wastewater and to air.'},
{id:'q38',m:'m4',l:'m4l3',t:'sc',q:'Water is standing on the surface of a trickling filter. This is called ponding, and the usual first response is to:',
 o:['Increase recirculation to flush the media','Shut the filter down for a week','Reduce recirculation to dry it out','Add coagulant to the filter influent'],a:0,
 e:'Ponding means the media voids are plugged with excess biofilm. Increasing recirculation flushes the media; raking, flushing or dose-flooding also help.'},
{id:'q39',m:'m4',l:'m4l3',t:'mc',q:'Why must a clarifier always follow a trickling filter or RBC?',
 o:['To remove the biofilm solids that slough off the media','To disinfect the effluent','To add oxygen to the effluent','To remove grit'],a:0,
 e:'Fixed-film biomass continually sloughs off the media. Without a clarifier those solids leave in the effluent.'},
{id:'q40',m:'m4',l:'m4l4',t:'mc',q:'A facultative lagoon is characterised by:',
 o:['An aerobic upper layer and an anaerobic bottom layer','A fully aerobic profile top to bottom','A fully anaerobic profile top to bottom','Mechanical aeration throughout'],a:0,
 e:'Facultative = aerobic on top (wind and algal photosynthesis), anaerobic at the bottom, facultative in between. The most common lagoon type.'},
{id:'q41',m:'m4',l:'m4l4',t:'sc',q:'Lagoon effluent has high TSS but low BOD. The most likely cause is:',
 o:['Algae carryover in the effluent','Excessive influent grit','A failed disinfection system','Sludge bulking'],a:0,
 e:'Algae are suspended solids and are the classic cause of high TSS from a lagoon that is otherwise treating well.'},
{id:'q42',m:'m4',l:'m4l5',t:'sc',q:'Chunks of sludge are floating to the surface of the SECONDARY clarifier with gas bubbles attached. The most likely cause is:',
 o:['Denitrification releasing nitrogen gas in the sludge blanket','Excessive chlorine residual carried over from the contact chamber','Grit accumulating beneath the clarifier rake mechanism','Unusually low influent BOD reaching the aeration basin'],a:0,
 e:'In a secondary clarifier, rising sludge with gas bubbles is classically denitrification. Increase RAS to shorten blanket detention time.'},
{id:'q43',m:'m4',l:'m4l5',t:'sc',q:'The sludge blanket in the secondary clarifier is climbing toward the weirs. The first adjustment to consider is:',
 o:['Increase the RAS rate','Decrease the RAS rate','Increase aeration basin DO to 8 mg/L','Stop wasting entirely'],a:0,
 e:'RAS rate controls the blanket. Increase RAS to pull solids out faster, then investigate the underlying cause (bulking, hydraulic overload, collector failure).'},
{id:'q44',m:'m4',l:'m4l5',t:'mc',q:'A secondary clarifier must perform two competing functions. They are:',
 o:['Clarification and thickening','Aeration and settling','Disinfection and filtration','Screening and grit removal'],a:0,
 e:'It must produce clear effluent (clarify) AND concentrated RAS (thicken). Pushing hard on one degrades the other.'},

/* ================= MODULE 5 ================= */
{id:'q45',m:'m5',l:'m5l1',t:'mc',q:'Coagulation requires which type of mixing, and why?',
 o:['Rapid mixing, because charge neutralisation happens in seconds','Slow mixing, because floc is fragile','No mixing at all','Intermittent mixing over several hours'],a:0,
 e:'Coagulation is a charge reaction occurring in seconds, so the coagulant must be dispersed violently and instantly. Flocculation is the slow, gentle step.'},
{id:'q46',m:'m5',l:'m5l1',t:'mc',q:'Colloidal particles remain suspended indefinitely because they:',
 o:['Carry like electrical surface charges and repel each other','Are lighter than water','Are chemically bonded to water molecules','Are too large to settle'],a:0,
 e:'Colloids carry (usually negative) surface charges. Like charges repel, preventing the particles from colliding and growing.'},
{id:'q47',m:'m5',l:'m5l1',t:'sc',q:'You are dosing PACl but no floc forms and the water stays hazy. What should you check FIRST?',
 o:['pH — the coagulant may be outside its effective range','Whether the effluent pump is running','The chlorine residual','The digester temperature'],a:0,
 e:'pH first, always. Outside the coagulant\'s effective window no dose will work. Only after pH is confirmed should you adjust dose or mixing.'},
{id:'q48',m:'m5',l:'m5l1',t:'sc',q:'Good floc forms in the flocculation basin but breaks apart before reaching the settling tank. The most likely cause is:',
 o:['Excessive mixing energy or shear after flocculation','Insufficient coagulant dose','pH too high','Detention time too long'],a:0,
 e:'Floc is fragile. Too much paddle speed, or shear through a pump or narrow piping after flocculation, tears it apart. Reduce mixing energy.'},
{id:'q49',m:'m5',l:'m5l1',t:'mc',q:'Metal salt coagulants such as alum and ferric chloride:',
 o:['Consume alkalinity and lower pH','Add alkalinity and raise pH','Have no effect on pH','Raise pH only in cold water'],a:0,
 e:'Metal salts hydrolyse and consume alkalinity, driving pH down. In low-alkalinity water this can crash the pH and stop coagulation entirely.'},
{id:'q50',m:'m5',l:'m5l2',t:'mc',q:'In a jar test, the "best" jar is the one that shows:',
 o:['Rapid formation of large dense floc and the clearest supernatant','The greatest quantity of foam on the surface of the jar','The darkest colour remaining in the settled water','The highest final pH measured after settling'],a:0,
 e:'Judge by floc formation speed, floc size/density and clarity of the settled water — and confirm the clarity objectively with a turbidimeter.'},
{id:'q51',m:'m5',l:'m5l2',t:'calc',q:'A plant treats 3.0 ML/day and requires a coagulant dose of 25 mg/L. How many kg/day of coagulant are needed?',
 o:['75 kg/day','7.5 kg/day','750 kg/day','8.3 kg/day'],a:0,
 e:'kg/day = dose (mg/L) × flow (ML/day) = 25 × 3.0 = 75 kg/day. This metric form is clean because 1 mg/L in 1 ML = 1 kg.'},
{id:'q52',m:'m5',l:'m5l2',t:'calc',q:'You need 75 kg/day of active chemical, but your product is a 50% solution. How much solution per day must you feed?',
 o:['150 kg/day','37.5 kg/day','75 kg/day','300 kg/day'],a:0,
 e:'Divide by decimal purity: 75 ÷ 0.50 = 150 kg/day of solution. A weaker solution always means MORE product.'},
{id:'q53',m:'m5',l:'m5l3',t:'mc',q:'Alkalinity is best described as:',
 o:['Water\'s capacity to resist a change in pH','The current pH of the water','The amount of dissolved oxygen present','The hardness of the water'],a:0,
 e:'Alkalinity is the BUFFER. pH tells you where you are; alkalinity tells you how hard it is to move you.'},
{id:'q54',m:'m5',l:'m5l3',t:'sc',q:'Plant pH swings wildly with even tiny chemical additions. The best corrective action is to:',
 o:['Add alkalinity to build buffering capacity','Add more acid to stabilise it','Increase aeration','Reduce the influent flow'],a:0,
 e:'Wild swings from small additions is the signature of low alkalinity. Build the buffer rather than chasing pH up and down.'},
{id:'q55',m:'m5',l:'m5l3',t:'mc',q:'Approximately how much alkalinity does nitrification consume?',
 o:['7.1 mg/L per mg/L of ammonia-nitrogen oxidised','0.5 mg/L per mg/L of ammonia-nitrogen','71 mg/L per mg/L of ammonia-nitrogen','It produces alkalinity rather than consuming it'],a:0,
 e:'About 7.1 mg alkalinity per mg of ammonia-N oxidised. In soft water this alone can crash plant pH, so alkalinity must be monitored.'},
{id:'q56',m:'m5',l:'m5l3',t:'mc',q:'When diluting a concentrated acid, the correct procedure is:',
 o:['Always add acid to water','Always add water to acid','Either order is acceptable','Mix them simultaneously in equal streams'],a:0,
 e:'ALWAYS add acid TO water. The reaction is violently exothermic; adding water to acid can boil and spatter acid explosively.'},

/* ================= MODULE 6 ================= */
{id:'q57',m:'m6',l:'m6l1',t:'mc',q:'Which of these is NOT a normal trigger for backwashing a filter?',
 o:['The influent flow rate has decreased','Headloss has reached the set limit','Turbidity breakthrough is detected','The maximum run time has been reached'],a:0,
 e:'The three normal triggers are high headloss, turbidity breakthrough and maximum run time. A drop in flow is not a backwash trigger.'},
{id:'q58',m:'m6',l:'m6l1',t:'mc',q:'A multimedia filter bed is layered with:',
 o:['Coarse, lighter media on top and finer, denser media below','Fine media on top and coarse below','Uniform media throughout','Coarse media only'],a:0,
 e:'Coarse light anthracite on top, finer denser sand below, sometimes garnet at the bottom. This lets the full bed depth do work rather than plugging the surface.'},
{id:'q59',m:'m6',l:'m6l1',t:'sc',q:'Mudballs have formed in a granular media filter. The root cause is usually:',
 o:['Inadequate backwashing','Excessive backwashing','Too much chlorine in the influent','Media that is too coarse'],a:0,
 e:'Mudballs form when backwash does not fully fluidise and scour the bed — rate too low, duration too short, or no air scour.'},
{id:'q60',m:'m6',l:'m6l1',t:'mc',q:'Activated carbon removes dissolved organics primarily by:',
 o:['Adsorption onto the carbon surface','Straining particles from the water','Biological oxidation','Chemical precipitation'],a:0,
 e:'Adsorption — molecules adhere to the carbon\'s vast internal surface area. Carbon eventually exhausts and must be replaced or regenerated.'},
{id:'q61',m:'m6',l:'m6l2',t:'mc',q:'Chlorine disinfection is MOST effective at:',
 o:['Lower pH, because more hypochlorous acid (HOCl) is present','Higher pH, because more hypochlorite ion is present','pH above 9.5','pH is irrelevant to chlorine effectiveness'],a:0,
 e:'At lower pH the equilibrium favours HOCl, which is far the stronger disinfectant. Above about pH 8 effectiveness falls off sharply.'},
{id:'q62',m:'m6',l:'m6l2',t:'mc',q:'"Free available chlorine" consists of:',
 o:['Hypochlorous acid (HOCl) and hypochlorite ion (OCl⁻)','Monochloramine and dichloramine','Chloride ion only','Chlorine gas dissolved in water only'],a:0,
 e:'Free available chlorine = HOCl + OCl⁻. Chloramines are COMBINED chlorine and are much weaker disinfectants.'},
{id:'q63',m:'m6',l:'m6l2',t:'mc',q:'Beyond the breakpoint, additional chlorine added to wastewater:',
 o:['Remains as free available chlorine residual','Is consumed forming chloramines','Produces no residual at all','Converts entirely to chloride'],a:0,
 e:'Past the breakpoint, demand is satisfied and chloramines have been destroyed, so further chlorine remains as free residual.'},
{id:'q64',m:'m6',l:'m6l2',t:'sc',q:'A UV system is failing bacteriological limits. Which should you check FIRST?',
 o:['Whether the quartz sleeves are fouled','Whether the chlorine dose is adequate','The digester gas production','The grit chamber velocity'],a:0,
 e:'Fouled quartz sleeves are the number one cause of UV underperformance. Then check lamp age/hours and UV transmittance.'},
{id:'q65',m:'m6',l:'m6l2',t:'sc',q:'Chlorine residual is at target but coliform results still fail. Which is the LEAST likely explanation?',
 o:['The chlorine dose is far too high','Short-circuiting in the contact chamber','High TSS shielding organisms from the chlorine','High pH reducing the proportion of HOCl'],a:0,
 e:'An excessive dose would not cause failures. Short-circuiting, particle shielding and high pH all reduce effective disinfection despite an adequate measured residual.'},
{id:'q66',m:'m6',l:'m6l2',t:'mc',q:'Two key advantages of UV disinfection over chlorination are:',
 o:['No chemical residual and no disinfection by-products','Lower capital cost and no electricity required','It provides a lasting residual in the receiving water','It removes suspended solids as well'],a:0,
 e:'UV leaves no residual (so no dechlorination needed) and creates no DBPs. It provides no lasting residual, which is a disadvantage in some applications.'},
{id:'q67',m:'m6',l:'m6l2',t:'calc',q:'A chlorine contact chamber holds 90 m³ and flow is 2,160 m³/day. What is the contact time in minutes?',
 o:['60 minutes','30 minutes','24 minutes','90 minutes'],a:0,
 e:'DT = V ÷ Q = 90 ÷ 2,160 = 0.04167 days. × 24 h = 1.0 hour = 60 minutes. Alternatively 2,160 m³/day ÷ 1,440 min/day = 1.5 m³/min; 90 ÷ 1.5 = 60 min.'},

/* ================= MODULE 7 ================= */
{id:'q68',m:'m7',l:'m7l1',t:'mc',q:'Waste activated sludge (WAS) typically has a solids content of:',
 o:['0.5 to 1.5%','3 to 7%','15 to 30%','40 to 60%'],a:0,
 e:'WAS is 0.5–1.5% solids — over 98% water — and is the hardest sludge to thicken and dewater. Primary sludge is 3–7%; dewatered cake is 15–30%.'},
{id:'q69',m:'m7',l:'m7l1',t:'mc',q:'Mesophilic anaerobic digestion operates at approximately:',
 o:['35 °C','15 °C','55 °C','75 °C'],a:0,
 e:'Mesophilic ≈ 35 °C (95 °F) with 15–30 days detention. Thermophilic ≈ 55 °C and is faster but more sensitive.'},
{id:'q70',m:'m7',l:'m7l1',t:'mc',q:'Digester biogas is composed primarily of:',
 o:['Methane and carbon dioxide','Oxygen and nitrogen','Hydrogen and helium','Chlorine and ammonia'],a:0,
 e:'Roughly 60–70% methane and 30–40% carbon dioxide, with traces of H₂S. The methane makes it both valuable and explosive.'},
{id:'q71',m:'m7',l:'m7l1',t:'sc',q:'Digester gas production is falling and volatile acids are rising. This indicates:',
 o:['The digester is souring — acid formers are outpacing methane formers','The digester is operating perfectly','Excessive alkalinity has been added','The digester temperature is too low to matter'],a:0,
 e:'A rising volatile acids to alkalinity ratio is the earliest warning of digester souring. Reduce feed, check temperature and add alkalinity if needed.'},
{id:'q72',m:'m7',l:'m7l2',t:'mc',q:'Liquid removed by a centrifuge during dewatering is called:',
 o:['Centrate','Filtrate','Subnatant','Supernatant'],a:0,
 e:'Centrifuge = centrate. Belt/plate press = filtrate. Thickener = subnatant. All return to the head of the plant.'},
{id:'q73',m:'m7',l:'m7l2',t:'sc',q:'Plant upsets consistently occur a few hours after the belt filter press runs. The most likely cause is:',
 o:['The filtrate return stream is a slug load of solids and ammonia','The press is removing too much water','The polymer is too dilute to matter','The dewatered cake is too dry'],a:0,
 e:'Return streams carry high solids and ammonia. Returned all at once they upset the plant. Equalise and meter the return steadily over the day.'},
{id:'q74',m:'m7',l:'m7l2',t:'mc',q:'Before mechanical dewatering, sludge almost always requires:',
 o:['Polymer conditioning','Chlorination','Aeration to saturation','pH reduction below 4'],a:0,
 e:'Polymer binds fine particles into larger flocs that release water. Polymer dose and mixing are the biggest factors in dewatering performance.'},

/* ================= MODULE 8 ================= */
{id:'q75',m:'m8',l:'m8l1',t:'sc',q:'A pump makes a noise like gravel rattling through it and the discharge pressure is erratic. This indicates:',
 o:['Cavitation','Normal operation under high load','Excessive lubrication','A closed discharge valve only'],a:0,
 e:'Gravel/marble noise plus erratic pressure is the textbook description of cavitation — vapour bubbles collapsing violently at the impeller.'},
{id:'q76',m:'m8',l:'m8l1',t:'sc',q:'Having identified cavitation, which side of the pump should you investigate?',
 o:['The suction side','The discharge side','The motor windings','The pump base grouting'],a:0,
 e:'Cavitation is caused by insufficient suction pressure: throttled/closed suction valve, plugged strainer, low wet-well level, excessive suction lift, or hot liquid.'},
{id:'q77',m:'m8',l:'m8l1',t:'mc',q:'Which statement about positive displacement pumps is correct?',
 o:['They must never be run against a closed discharge valve','Their flow drops sharply as head increases','They cannot be used for chemical metering','They do not require a pressure relief valve'],a:0,
 e:'A PD pump has no internal relief path. Deadheading it builds pressure until something ruptures. A pressure relief valve is mandatory.'},
{id:'q78',m:'m8',l:'m8l1',t:'mc',q:'As discharge head increases, the flow from a centrifugal pump:',
 o:['Decreases, following the pump curve','Increases proportionally','Remains constant','Stops immediately'],a:0,
 e:'Centrifugal pump flow falls as head rises. Positive displacement pumps hold near-constant flow regardless of head — the key difference between the families.'},
{id:'q79',m:'m8',l:'m8l1',t:'mc',q:'A properly adjusted packing gland should:',
 o:['Drip slowly to lubricate and cool the shaft','Be completely dry at all times','Leak in a steady stream','Be tightened until the shaft cannot turn'],a:0,
 e:'Packing needs a slow drip — roughly a drop every second or two — for lubrication and cooling. A dry gland burns the shaft sleeve. Mechanical seals, by contrast, should not leak.'},
{id:'q80',m:'m8',l:'m8l2',t:'mc',q:'Which valve is designed specifically for throttling flow?',
 o:['Globe valve','Gate valve','Check valve','Pressure relief valve'],a:0,
 e:'Globe = throttling. Gate = isolation only (throttling erodes the seat). Check = automatic backflow prevention. Relief = overpressure protection.'},
{id:'q81',m:'m8',l:'m8l2',t:'mc',q:'A check valve is used to:',
 o:['Prevent flow in the reverse direction','Regulate flow rate precisely','Isolate a line for maintenance','Relieve excess pressure'],a:0,
 e:'Check valves are automatic, one-direction valves that protect pumps from backflow and reverse rotation.'},
{id:'q82',m:'m8',l:'m8l2',t:'sc',q:'Motor amps on a sludge pump have crept up 12% over two months with no process change. This most likely indicates:',
 o:['A developing mechanical problem such as a clog or bearing wear','Improved pump efficiency','A calibration error in the flow meter','Normal seasonal variation'],a:0,
 e:'Rising amps mean the motor is working harder — clog, bearing wear, misalignment or rubbing. Investigate before it fails.'},
{id:'q83',m:'m8',l:'m8l2',t:'sc',q:'Blower discharge pressure is rising while delivered air flow falls. What do you check first?',
 o:['The blower inlet filter','The effluent weir level','The digester temperature','The chlorine residual'],a:0,
 e:'Check the cheap, common thing first: a plugged inlet filter starves the blower. Then look downstream at fouled diffusers.'},
{id:'q84',m:'m8',l:'m8l2',t:'mc',q:'Preventive maintenance records are important primarily because they:',
 o:['Demonstrate regulatory compliance and reveal equipment trends','Are only needed when equipment fails','Replace the need for operator training','Are optional at Class I facilities'],a:0,
 e:'PM records prove the plant was properly maintained and reveal developing trends. They are part of compliance, not optional paperwork.'},

/* ================= MODULE 9 ================= */
{id:'q85',m:'m9',l:'m9l1',t:'mc',q:'Which parameter MUST be measured on a grab sample immediately after collection?',
 o:['Dissolved oxygen','BOD₅','Total suspended solids','Total phosphorus'],a:0,
 e:'DO, pH, temperature and chlorine residual all change the moment the sample leaves the process, so they must be grab samples measured immediately.'},
{id:'q86',m:'m9',l:'m9l1',t:'mc',q:'A composite sample that best represents daily mass loading is:',
 o:['Flow-proportional','Time-proportional with equal portions','A single grab at peak flow','A single grab at minimum flow'],a:0,
 e:'Weighting each portion by flow means the composite reflects true mass load rather than over-representing low-flow periods.'},
{id:'q87',m:'m9',l:'m9l1',t:'sc',q:'Which bottle must NEVER be rinsed with the sample before collection?',
 o:['A sterile bacteriological bottle','A plastic TSS bottle','A composite sampler carboy','A BOD bottle used for a plant effluent sample'],a:0,
 e:'Rinsing destroys sterility, and also removes any preservative or dechlorinating agent already in the bottle.'},
{id:'q88',m:'m9',l:'m9l1',t:'mc',q:'Chain of custody documentation is required for:',
 o:['Samples used for regulatory or legal purposes','All samples without exception','Only samples analysed off site','Only samples that fail a limit'],a:0,
 e:'Any sample that may be used for regulatory or legal purposes needs an unbroken, documented chain of custody.'},
{id:'q89',m:'m9',l:'m9l2',t:'mc',q:'The BOD₅ test is conducted:',
 o:['5 days at 20 °C in the dark','5 hours at 35 °C in the light','20 days at 5 °C in the dark','2 hours at 150 °C'],a:0,
 e:'5 days, 20 °C, dark. Darkness prevents algae from producing oxygen and corrupting the result. All three conditions are examinable.'},
{id:'q90',m:'m9',l:'m9l2',t:'mc',q:'Total suspended solids samples are dried at what temperature?',
 o:['103–105 °C','550 °C','20 °C','250 °C'],a:0,
 e:'Dry at 103–105 °C for TSS. Ignite at 550 °C to determine the volatile fraction. Know both numbers.'},
{id:'q91',m:'m9',l:'m9l2',t:'sc',q:'TSS results from the same sample vary widely between duplicates. Which is the LEAST likely cause?',
 o:['The wastewater temperature was 18 °C instead of 20 °C','The sample was not mixed before pouring','The filter was not dried to a constant weight','The analytical balance is out of calibration'],a:0,
 e:'A small temperature difference does not affect gravimetric TSS. Poor mixing, incomplete drying and balance error all directly cause poor reproducibility.'},
{id:'q92',m:'m9',l:'m9l3',t:'sc',q:'You have made three process changes at once and effluent quality improved. The problem with this is:',
 o:['You cannot tell which change was responsible','Improvement is never a problem','It violates the plant permit automatically','It requires immediate regulatory reporting'],a:0,
 e:'Change one variable at a time. Otherwise you learn nothing, and cannot reproduce the fix or undo a harmful change.'},
{id:'q93',m:'m9',l:'m9l3',t:'mc',q:'Good process control practice is to make changes that are:',
 o:['Small, one at a time, then wait long enough to evaluate','Large, so the effect is obvious quickly','Multiple and simultaneous, to save time','Only made when a permit limit is exceeded'],a:0,
 e:'Biology responds over days. Small single changes with adequate evaluation time prevent the oscillation that wrecks plants.'},
{id:'q94',m:'m9',l:'m9l3',t:'mc',q:'Operating logs and lab records are best described as:',
 o:['A legal requirement and the plant\'s record of compliance','Internal notes with no regulatory significance','Optional if SCADA is installed','Required only during inspections'],a:0,
 e:'Records are legally required and are the plant\'s proof of proper operation. Falsifying them is among the most serious operator offences.'},

/* ================= MODULE 10 ================= */
{id:'q95',m:'m10',l:'m10l1',t:'mc',q:'The correct order for testing a confined space atmosphere is:',
 o:['Oxygen, then flammable, then toxic','Toxic, then flammable, then oxygen','Flammable, then oxygen, then toxic','Any order is acceptable'],a:0,
 e:'Oxygen first — a flammable gas meter needs oxygen to read correctly, so an oxygen-deficient atmosphere makes the flammable reading unreliable.'},
{id:'q96',m:'m10',l:'m10l1',t:'mc',q:'The acceptable oxygen range for confined space entry is:',
 o:['19.5% to 23.5%','15% to 25%','10% to 30%','21% exactly'],a:0,
 e:'Below 19.5% is oxygen deficient. Above 23.5% is oxygen enriched and a severe fire/explosion hazard. Both ends are examinable.'},
{id:'q97',m:'m10',l:'m10l1',t:'sc',q:'While working in a wet well you notice the rotten-egg smell has disappeared. You should:',
 o:['Evacuate immediately — H₂S deadens the sense of smell at dangerous concentrations','Continue working, since the hazard has clearly passed','Remove your respirator briefly to confirm the odour is gone','Increase the pump rate to draw the remaining gas away'],a:0,
 e:'Loss of the smell means the concentration has risen high enough to paralyse your olfactory nerve. This is MORE dangerous, not less. Leave at once.'},
{id:'q98',m:'m10',l:'m10l1',t:'sc',q:'A worker collapses inside a confined space. The correct action is:',
 o:['Do not enter; call for help and use retrieval equipment from outside','Enter immediately to pull them out','Enter with a coworker for safety','Wait to see if they recover on their own'],a:0,
 e:'The majority of confined space deaths are would-be rescuers. Never enter without proper training and equipment. Use the retrieval system from outside.'},
{id:'q99',m:'m10',l:'m10l2',t:'mc',q:'In the hierarchy of controls, personal protective equipment ranks:',
 o:['Last — it is the final line of defence','First — it is the most reliable control','Second, after administrative controls','It is not part of the hierarchy'],a:0,
 e:'Elimination → Substitution → Engineering → Administrative → PPE. PPE protects only the individual and only if worn correctly.'},
{id:'q100',m:'m10',l:'m10l2',t:'mc',q:'Under WHMIS 2015, a container that a chemical has been decanted into on site requires:',
 o:['A workplace label','No label, as it stays on site','Only the supplier label from the original drum','A label only if stored more than 30 days'],a:0,
 e:'Supplier labels go on original containers; workplace labels are required on any container filled on site. All containers must be labelled.'},
{id:'q101',m:'m10',l:'m10l2',t:'sc',q:'During lockout/tagout, who may remove a personal lock?',
 o:['Only the worker who applied it','Any supervisor','Any qualified electrician','The next shift operator'],a:0,
 e:'Each worker applies their own lock, and only that worker removes it. This guarantees no one is re-energising equipment someone else is working on.'},
{id:'q102',m:'m10',l:'m10l2',t:'mc',q:'Two steps commonly missed in a lockout/tagout procedure are:',
 o:['Releasing stored energy and verifying zero energy','Notifying the supplier and filing a permit','Testing the atmosphere and posting a guard','Calibrating meters and recording amps'],a:0,
 e:'Stored energy (pressure, springs, gravity, capacitors, heat) must be released, and zero energy must be verified by attempting to start the equipment.'},
{id:'q103',m:'m10',l:'m10l2',t:'sc',q:'A caustic soda splash reaches an operator\'s forearm. First aid is to:',
 o:['Flush with water for at least 15 minutes and seek medical attention','Neutralise it with a weak acid','Apply an oil-based ointment immediately','Wipe it off with a dry cloth and continue working'],a:0,
 e:'Flush with copious water for at least 15 minutes. Never attempt chemical neutralisation on skin — it generates heat and worsens the injury.'},

/* ================= MODULE 11 ================= */
{id:'q104',m:'m11',l:'m11l1',t:'mc',q:'Which federal legislation prohibits depositing deleterious substances into waters frequented by fish?',
 o:['The Fisheries Act','The Environmental Management Act','The Municipal Wastewater Regulation','The Drinking Water Protection Act'],a:0,
 e:'The Fisheries Act is the federal foundation, with the Wastewater Systems Effluent Regulations (WSER) setting national baseline effluent standards under it.'},
{id:'q105',m:'m11',l:'m11l1',t:'mc',q:'In British Columbia, municipal wastewater discharge is primarily governed by:',
 o:['The Environmental Management Act and the Municipal Wastewater Regulation','The federal Fisheries Act acting alone without provincial regulation','The Canada Water Act together with the Drinking Water Protection Act','Local municipal bylaws with no provincial or federal involvement'],a:0,
 e:'The Environmental Management Act is BC\'s enabling legislation, with the Municipal Wastewater Regulation setting the specific requirements.'},
{id:'q106',m:'m11',l:'m11l1',t:'mc',q:'To maintain EOCP certification, an operator must:',
 o:['Earn Continuing Education Units (CEUs)','Re-write the certification exam annually','Work a minimum of 60 hours per week','Obtain a professional engineering licence'],a:0,
 e:'EOCP certification is renewed by accumulating CEUs. Track them as you earn them rather than scrambling near renewal.'},
{id:'q107',m:'m11',l:'m11l1',t:'sc',q:'A sample shows the effluent BOD limit was exceeded. The correct response is to:',
 o:['Verify the result, correct the cause, document, and report within the required timeframe','Wait for the next monthly report to mention it','Re-sample until a passing result is obtained and report that','Adjust the recorded value to within the limit'],a:0,
 e:'Verify, correct, document, report promptly. Selectively re-sampling for a passing result or altering data is falsification — the most serious operator offence.'},
{id:'q108',m:'m11',l:'m11l1',t:'mc',q:'The level of operator certification a facility requires is determined by:',
 o:['The facility classification, based on size and complexity','The number of employees','The age of the plant','The volume of chemicals stored'],a:0,
 e:'Plants are classified by size and complexity, and that classification sets the required certification level and the operator in responsible charge.'},

/* ================= MODULE 12 ================= */
{id:'q109',m:'m12',l:'m12l1',t:'mc',q:'On the WPI/EOCP standardized exam, formulas are:',
 o:['Provided on a formula/conversion sheet at the exam','Required to be memorised completely','Not needed at all','Provided only for Class III and IV exams'],a:0,
 e:'A formula/conversion table is provided. The skill being tested is selecting the right formula and handling units — practise USING the sheet.'},
{id:'q110',m:'m12',l:'m12l1',t:'calc',q:'Convert 3,750 L to cubic metres.',
 o:['3.75 m³','37.5 m³','375 m³','0.375 m³'],a:0,
 e:'1 m³ = 1,000 L, so 3,750 ÷ 1,000 = 3.75 m³. Missing this conversion is the single most common source of factor-of-1,000 errors.'},
{id:'q111',m:'m12',l:'m12l1',t:'calc',q:'A circular tank is 12 m in diameter and 4 m deep. What is its volume?',
 o:['452 m³','1,810 m³','151 m³','48 m³'],a:0,
 e:'Radius = 12 ÷ 2 = 6 m. Area = π × 6² = 113.1 m². Volume = 113.1 × 4 = 452 m³. Using the diameter instead of the radius gives 1,810 — the classic trap answer.'},
{id:'q112',m:'m12',l:'m12l1',t:'calc',q:'A plant treats 6.0 ML/day with an influent TSS of 240 mg/L. What is the TSS load in kg/day?',
 o:['1,440 kg/day','144 kg/day','14,400 kg/day','40 kg/day'],a:0,
 e:'kg/day = mg/L × ML/day = 240 × 6.0 = 1,440 kg/day.'},
{id:'q113',m:'m12',l:'m12l1',t:'calc',q:'An aeration basin holds 1,200 m³ and receives 3,600 m³/day. What is the detention time in hours?',
 o:['8 hours','3 hours','0.33 hours','12 hours'],a:0,
 e:'DT = V ÷ Q = 1,200 ÷ 3,600 = 0.333 days × 24 = 8 hours.'},
{id:'q115',m:'m2',l:'m2l4',t:'mc',q:'The primary purpose of flow equalization is to:',
 o:['Dampen flow and load peaks so downstream processes see a steadier rate','Remove grit from the wastewater','Disinfect the wastewater before primary treatment','Increase the organic strength of the influent'],a:0,
 e:'Equalization stores wastewater and releases it at a controlled rate, flattening both hydraulic and organic peaks. This protects clarifiers from overload, stabilises chemical dosing and protects disinfection contact time.'},
{id:'q116',m:'m2',l:'m2l4',t:'sc',q:'An equalization basin has developed strong odours and solids are accumulating on the bottom. The most likely cause is:',
 o:['Inadequate mixing or aeration in the basin','The basin is too large for the plant','The influent contains too much dissolved oxygen','The transfer pumps are running too fast'],a:0,
 e:'Equalization basins must be mixed, and usually aerated. Without mixing, solids settle out and the contents go septic, turning the basin into an odour source that also needs cleaning.'},
{id:'q117',m:'m2',l:'m2l4',t:'sc',q:'A plant using a comminutor still finds rags wrapped around its downstream pump impellers. The best explanation is:',
 o:['Shredded rag fibres re-knit into ropes because the comminutor removes nothing','The comminutor is grinding the rags too finely','Rags are entering downstream of the comminutor only','Comminutors are designed to pass rags intact'],a:0,
 e:'A comminutor macerates solids but leaves every fibre in the flow. Rag fibres readily re-form into ropes that wrap impellers and rake mechanisms. This is exactly why many plants replace comminutors with fine screens, which remove the material instead.'},
{id:'q118',m:'m2',l:'m2l4',t:'mc',q:'In-line equalization differs from side-line equalization in that in-line:',
 o:['Passes all flow through the basin, damping both flow and concentration','Passes none of the flow through the basin under normal conditions','Is always smaller and cheaper to build than the side-line arrangement','Requires no mixing because the flow is already fully blended'],a:0,
 e:'In-line equalization routes all flow through the basin and so damps both flow rate and concentration. Side-line diverts only flow above a set rate, which is smaller and cheaper but shaves peaks only.'},
{id:'q119',m:'m12',l:'m12l1',t:'calc',q:'US UNITS: A plant treats 2.0 MGD with an influent BOD of 180 mg/L. What is the BOD load in lbs/day?',
 o:['3,002 lbs/day','360 lbs/day','1,501 lbs/day','30,024 lbs/day'],a:0,
 e:'lbs/day = mg/L x MGD x 8.34 = 180 x 2.0 x 8.34 = 3,002 lbs/day. The 8.34 is pounds per US gallon of water. Exam calculations are given in both US and metric units, so practise both forms.'},
{id:'q120',m:'m12',l:'m12l1',t:'calc',q:'US UNITS: A circular clarifier 70 ft in diameter treats 1.2 MGD. What is the surface overflow rate in gpd/ft²?',
 o:['312 gpd/ft²','78 gpd/ft²','5,455 gpd/ft²','1,200 gpd/ft²'],a:0,
 e:'r = 35 ft. Area = pi x 35² = 3,848 ft². SOR = 1,200,000 gpd ÷ 3,848 = 312 gpd/ft². Remember to halve the diameter — using 70 ft as the radius is the classic error.'},
{id:'q121',m:'m12',l:'m12l1',t:'calc',q:'US UNITS: A tank is 30 ft long, 15 ft wide and holds water 8 ft deep. What is the volume in gallons?',
 o:['26,928 gallons','3,600 gallons','480 gallons','269,280 gallons'],a:0,
 e:'V = 30 x 15 x 8 = 3,600 ft³. Convert using 7.48 gallons per ft³: 3,600 x 7.48 = 26,928 gallons.'},
{id:'q122',m:'m12',l:'m12l1',t:'mc',q:'On the WPI standardized exam, calculation questions are presented:',
 o:['In both US Standard and Metric units, solvable in either system','In metric units only','In US Standard units only','In whichever units the candidate requests'],a:0,
 e:'Calculation items appear in US Standard units first with metric following in parentheses, and each item can be solved independently in either system. Work in whichever system you are faster in, but be fluent in both.'},
{id:'q123',m:'m8',l:'m8l2',t:'sc',q:'Why must standby pumps, motors and generators be started and run on a regular schedule?',
 o:['Equipment that sits idle seizes, loses prime or fails to start when it is finally needed','To use up the fuel before it expires','Because regulations require continuous duty on all equipment','To increase the total running hours recorded for the plant'],a:0,
 e:'Standby equipment is only worth having if it starts. Idle pumps seize, bearings corrode, batteries flatten and fuel degrades. Regular exercising under load is a core operator duty and appears on EOCP sample exams.'},
{id:'q124',m:'m8',l:'m8l2',t:'sc',q:'An operator finds the chemical day tank will run empty over the weekend. The correct action is:',
 o:['Replenish the chemical stock before it runs out and record the delivery','Reduce the chemical dose so the remaining stock lasts longer','Shut the plant down until Monday','Wait until the tank is empty before ordering more'],a:0,
 e:'Maintaining chemical inventory is a routine operator duty. Running out interrupts treatment and can cause a permit exceedance; cutting the dose to stretch stock deliberately under-treats the water.'},
{id:'q125',m:'m4',l:'m4l2',t:'sc',q:'Which appearance and odour indicate a healthy, good-quality activated sludge?',
 o:['Chocolate-brown colour with an earthy or musty odour','Black colour with a rotten-egg odour','Grey colour with a strong chlorine odour','Clear and colourless with no odour at all'],a:0,
 e:'Healthy activated sludge is chocolate-brown with a light earthy/musty smell. Black with a rotten-egg (hydrogen sulphide) odour means septic conditions and a loss of dissolved oxygen. This visual and olfactory check is a daily operator judgement.'},
{id:'q126',m:'m9',l:'m9l3',t:'sc',q:'Which of these is a routine DAILY operator duty at a treatment plant?',
 o:['Recording flows and lab results in the operating log and walking the plant to observe each process','Stripping and rebuilding the main influent pump and its drive','Recalculating the facility classification points for the plant','Preparing and submitting the plant discharge permit renewal'],a:0,
 e:'Daily duties are observation, monitoring and record keeping. Pump rebuilds are scheduled maintenance; classification and permit renewal are administrative events that happen rarely.'},
{id:'q127',m:'m3',l:'m3l1',t:'sc',q:'Routine cleaning of a settling basin and proper disposal of the collected sludge is important because:',
 o:['Accumulated sludge reduces effective tank volume and goes septic, degrading effluent quality','It improves the appearance of the plant for visitors','It is only needed if the plant is being inspected','Sludge left in place improves settling over time'],a:0,
 e:'Sludge left in a settling basin steals design volume, shortens effective detention time and turns septic, releasing odours and dissolved organics back into the flow. Removal and correct disposal is a routine duty, not an optional one.'},
{id:'q128',m:'m9',l:'m9l2',t:'sc',q:'An operator pours mixed liquor into a settling cylinder and reads the settled volume after 30 minutes. This test is used to judge:',
 o:['How well the sludge settles, which combined with MLSS gives the SVI','The chlorine demand of the effluent','The alkalinity of the influent','The grit content of the raw wastewater'],a:0,
 e:'This is the settleability (settleometer) test. It is the cheapest and fastest daily indicator of sludge condition, and with MLSS it gives the Sludge Volume Index.'},
{id:'q114',m:'m12',l:'m12l1',t:'calc',q:'Influent TSS is 260 mg/L; effluent TSS is 13 mg/L. What is the percent removal?',
 o:['95%','5%','247%','87%'],a:0,
 e:'(260 − 13) ÷ 260 × 100 = 247 ÷ 260 × 100 = 95%.'}
];

window.QUESTIONS = QUESTIONS;
